---
title: "Very Interesting Document"
author: "Robert"
date: "2022-10-31"
output: github_document
# this line doesn't create HTML as output in files window
# Then one cannot post HMTL to GitHub for easy 

#output:
#  html_document:
#    keep_md: true

# to update to most current version of R
#   update.packages(ask = FALSE, checkBuilt = TRUE)


---

Hello World
Eat more beans!

# Square root & Exponents
```{r, eval=TRUE}
sqrt(81)
9^2
```

Simple graph


#load ggplot2
library(ggplot2)
# Cannot find function "ggplot" 


```{r, eval=TRUE}
#create data frame
df <- data.frame(x=c(1, 2, 4, 5, 7, 8, 9, 10),
                 y=c(12, 17, 27, 39, 50, 57, 66, 80))
#create scatterplot of x vs. y
ggplot(df, aes(x=x, y=y)) +
  geom_point()
```

Density Plot
# library
library(ggplot2)
library(dplyr)
library(hrbrthemes)

```{r, eval=TRUE}
# Stacked density plot:
ggplot(data=diamonds, aes(x=price, group=cut, fill=cut)) +
    geom_density(adjust=1.5, position="fill") +
    theme_ipsum() 
```

Ridge Lines

# library
library(ggridges)
library(ggplot2)
library(viridis)
library(hrbrthemes)

```{r, eval=TRUE}
# Plot
ggplot(lincoln_weather, aes(x = `Mean Temperature [F]`, y = `Month`, fill = ..x..)) +
  geom_density_ridges_gradient(scale = 3, rel_min_height = 0.01) +
  scale_fill_viridis(name = "Temp. [F]", option = "C") +
  labs(title = 'Temperatures in Lincoln NE in 2016') +
  theme_ipsum() +
    theme(
      legend.position="none",
      panel.spacing = unit(0.1, "lines"),
      strip.text.x = element_text(size = 8)
    )
```

THere is no working code.